[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "comparative2_experiments"
version = "0.0.1"
dependencies = [
    "torch>=2.0",
    "torchvision>=0.15",
    "hydra-core>=1.3",
    "optuna>=3.3",
    "wandb>=0.15",
    "omegaconf>=2.3",
    "transformers>=4.34",
    "scikit-learn>=1.3",
    "matplotlib>=3.8",
    "pillow>=10.0",
]
